### ISSUE TITLE
index.html gets downloaded  instead of served as html

### ISSUE THREAD

**Issue by nataibi** [aws-quickstart/quickstart-onica-cci-postcall-analytics#5]
after successfully deploying the Cloudfromation stack, the CloudFront url downloads the index.html instead of serving as html.

## replication steps
- successfully deploy the stack
- access the CloudFront url given via the output of the stack
- observe how the index.html gets downloaded insteam

**Comment by sshvans** [comment]
@nataibi Can you provide following details about the issue:
- Which region are you launching the stack in? If other than us-east-1, try launching in us-east-1.

**Comment by nataibi** [comment]
us-east-1 only

**Comment by sshvans** [comment]
Fixed in #6
